services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    env_file:
      - .dev.env
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test -d test_db -h localhost -p 5432" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: fastapi
    restart: always
    env_file:
      - .dev.env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  db_data: